import dash
from dash import html, dcc

# Setting the path for home page here. I call dash.register_page on each of my pages but I don't explicitly set a path for each. In the event you don't set a path, it is autogenerated based on the module name!

# Dash knows to include these files in the pages folder because we called 'dash.register_page within the desired files
dash.register_page(__name__, path='/')

# If we want to specify the page path, title, and link name you can do so like this:

# dash.register_page(
#     __name__,
#     path='/analytics-dashboard',
#     title='Our Analytics Dashboard',
#     name='Our Analytics Dashboard'
# )

layout = html.Div(children=[
    html.H1(children='This is the Home page'),
    html.Div(children=''' This is the Home page content '''),
])
